version: '3'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: segmentsalad
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data

volumes:
  postgresVolume: